os:
  - linux
  - osx

# Supported versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  matrix:
    - PY_BUILD_VERSION="27"
    - PY_BUILD_VERSION="35"
    - PY_BUILD_VERSION="36"
  global:
    - CUDA_VERSION: "7.5"
    - CUDA_SHORT_VERSION: "75"
  secure:
    - "r+bnh81VnmPYoYfedxFWOkrFcAFV32UIKr4Jjr4UAJUdcCH4YIC7BVkPFMiPUnY3/BLt2OEL3xqfsDVelUB/f0N3s3foeBdS14shdhoevu3Q1A2U4nV3uNsqzJg9rqQP3DiOB6YCjyCJErhaRa4t2AolBBGYel+Np/4cn+jETbbtH//X7UlBg5zA1d5OevsqtiGgAYFEXlrZU3/Tm4YhWxb+D8CszxPx6a8SKdtd/OaKrvz1REG5fBlOqDp/3o9iesD+oeP0eWvjDJpjW5vGcomwpHMY2TYoVdugppGLoKJk8tDgNMLecPOcLn8+1RyQmWlPy7291fxZApMx534ByysFytpS9ZrGtEQrzjkOP27MP3NMBQZfMmtZuXEw4saKBYuO5FVBLv4oKLx3L4EB9MrJJm8w3b2cjgAqsPujFEaiGbSgbgOOl4lcuiDGM46ktvXJl+DFn33lUk/9tdbttVuHayjUEZdWZByT50SA/0oDlcjKpzlFDv9bTLoZysn4GkN+RsfX2k11enlSvSZgZclzxdC9HtBLGRRuYUXeFW0FcdPeKUl6wmVuPVbgQcjThas5i6mz7DT5Ya5qnGakp37flFYYyg9SXwTZW5sBUfsJMMbSvZmOjOJXRAEyL5FXYLnhgpmvE8yi+nkxmdVrcHLXhYt4AkaCifMPRYyWjzM="

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-linux-anvil:texlive-amd30-cuda${CUDA_SHORT_VERSION};
    fi

script:
  # Retrieve conda-build-all
  - wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod u+x conda-build-all
  # Select upload destination
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia --dev --force";
    else
        export UPLOAD="--dev --force";
    fi
  - echo $UPLOAD
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST -e PY_BUILD_VERSION
            -t -i --rm -v `pwd`:/io jchodera/omnia-linux-anvil:texlive-amd30-cuda${CUDA_SHORT_VERSION}
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        echo "Building osx...";
        bash devtools/osx-build.sh;

    fi
