package:
  name: openmm-cuda75
  version: 7.3.0
  #version: 7.1.1

source:
  git_url: https://github.com/pandegroup/openmm.git
  #git_tag: c1a64aa


build:
  number: 0
  skip: True # [win]
  #features:
  #  - cuda75
  patches:
    - silent-cmake.patch
    - silent-doxygen.patch
    - silent-latexpdf.patch
    
extra:
  upload: dev
  force_upload: True

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake     [not win]
    - jom       [win]
    - python
    # Pin fftw3f to 3.3.3 to work around OSX py34 issues
    - fftw3f ==3.3.3 [osx]
    - fftw3f ==3.3.4 [win or linux]
    # swig is pinned to use omnia swig 3.0.8
    - swig ==3.0.8
    # on osx, need to install doxygen manually
    - doxygen   [not osx]
    # for building docs
    - sphinx ==1.5.6
    - sphinxcontrib-bibtex
    - sphinxcontrib-lunrsearch
    - sphinxcontrib-autodoc_doxygen
    - lxml
    - numpy
    # Get clang from conda-forge for linux only
    #- clangdev ==3.8.1 [linux]
    - clangdev [linux]

  run:
    - python
    - fftw3f
    - numpy

test:
  requires:
    - python
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
